"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { Bell, BookOpen, BrainCircuit, ChevronDown, ChevronRight, FileText, FileSearch, FlaskConical, Globe2, HeartPulse, Lightbulb, Map, Menu, Mic, Paperclip, Plus, Search, Send, Settings, ShieldCheck, Sparkles, Stethoscope, TrendingUp, UserRound, X } from "lucide-react";

type Mode = "Evidence synthesis" | "Paper analysis" | "Protocol builder" | "Statistical planning";
type Project = { id: string; name: string; question: string | null };
type Document = { id: string; originalName: string; byteSize: number; processingStatus: string };
const modes: { name: Mode; description: string; prompt: string }[] = [
  { name: "Evidence synthesis", description: "Find and assess current research", prompt: "What would you like to investigate? I’ll separate established findings from uncertainty and cite only sources we can verify." },
  { name: "Paper analysis", description: "Appraise a study, not just summarize it", prompt: "Attach a paper or paste its abstract. I’ll assess the design, risk of bias, applicability, and what the study does not prove." },
  { name: "Protocol builder", description: "Turn a question into a rigorous protocol", prompt: "Share your research idea. We’ll shape a focused question, appropriate design, outcomes, and safeguards together." },
  { name: "Statistical planning", description: "Plan analyses with assumptions visible", prompt: "Tell me the outcome, design, population, and estimand. I’ll help draft a transparent analysis plan." },
];
const prompts = ["Find current evidence", "Analyze a paper", "Build a PICO question", "Create a search strategy"];

export default function Home() {
  const [mode, setMode] = useState<Mode>("Evidence synthesis"); const [question, setQuestion] = useState(""); const [messages, setMessages] = useState<string[]>([]); const [reply, setReply] = useState(""); const [sources, setSources] = useState<{ id: string; title: string; journal: string | null; year: string | null; url: string; verificationStatus: "verified" | "unverified" }[]>([]); const [projects, setProjects] = useState<Project[]>([]); const [documents, setDocuments] = useState<Document[]>([]); const [analysis, setAnalysis] = useState(""); const [showProjectForm, setShowProjectForm] = useState(false); const [projectName, setProjectName] = useState(""); const [projectStatus, setProjectStatus] = useState(""); const fileInput = useRef<HTMLInputElement>(null);
  const active = useMemo(() => modes.find((item) => item.name === mode)!, [mode]);
  useEffect(() => { void fetch("/api/projects").then(async (response) => { if (response.ok) setProjects((await response.json() as { projects: Project[] }).projects); }).catch(() => undefined); }, []);
  useEffect(() => { void fetch("/api/documents").then(async (response) => { if (response.ok) setDocuments((await response.json() as { documents: Document[] }).documents); }).catch(() => undefined); }, []);
  const createProject = async () => { const name = projectName.trim(); if (name.length < 3) { setProjectStatus("Enter at least 3 characters."); return; } setProjectStatus("Saving…"); try { const response = await fetch("/api/projects", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ name, question: question.trim() || undefined }) }); const result = await response.json() as { project?: Project; error?: string }; if (!response.ok || !result.project) { setProjectStatus(result.error ?? "Unable to save project."); return; } setProjects((current) => [result.project!, ...current]); setProjectName(""); setShowProjectForm(false); setProjectStatus(""); } catch { setProjectStatus("Project storage is unavailable."); } };
  const uploadDocument = async (file: File) => { setReply("Uploading PDF securely…"); const data = new FormData(); data.append("file", file); try { const response = await fetch("/api/documents", { method: "POST", body: data }); const result = await response.json() as { document?: Document; error?: string }; if (!response.ok || !result.document) { setReply(result.error ?? "The document was not uploaded."); return; } setDocuments((current) => [result.document!, ...current]); setReply("PDF uploaded and queued for isolated extraction. Its contents have not yet been used to generate claims."); } catch { setReply("The document service is unavailable. No file was saved."); } };
  const analyzeDocument = async (document: Document) => { setReply("Analyzing the PDF as untrusted research material…"); setAnalysis(""); try { const response = await fetch("/api/documents/" + document.id + "/analyze", { method: "POST" }); const result = await response.json() as { analysis?: string; error?: string }; if (!response.ok || !result.analysis) { setReply(result.error ?? "The paper could not be analyzed."); return; } setDocuments((current) => current.map((item) => item.id === document.id ? { ...item, processingStatus: "analyzed" } : item)); setAnalysis(result.analysis); setReply("Paper analysis complete. Verify important claims against the original PDF."); } catch { setReply("The document analysis service is unavailable."); } };
  const openDocumentAnalysis = async (document: Document) => { if (document.processingStatus !== "analyzed") { await analyzeDocument(document); return; } setReply("Loading saved paper analysis…"); try { const response = await fetch("/api/documents/" + document.id + "/analyze"); const result = await response.json() as { analysis?: { content?: string }; error?: string }; if (!response.ok || !result.analysis?.content) { setReply(result.error ?? "The saved analysis could not be loaded."); return; } setAnalysis(result.analysis.content); setReply("Saved paper analysis loaded. Verify important claims against the original PDF."); } catch { setReply("The saved analysis is unavailable."); } };
  const submit = async () => { const value = question.trim(); if (!value) return; setMessages((current) => [...current, value]); setQuestion(""); setReply("Searching current literature…"); setSources([]); try { const response = await fetch("/api/research", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ mode, question: value }) }); const result = await response.json() as { message?: string; error?: string; sources?: { id: string; title: string; journal: string | null; year: string | null; url: string; verificationStatus: "verified" | "unverified" }[] }; setReply(result.message ?? result.error ?? "The research service could not process that request."); setSources(result.sources ?? []); } catch { setReply("The research service is unavailable. No claims or citations were generated."); } };
  const areas = [
    ["Digital Health", "32%", "2,634 papers", Stethoscope, "cyan"], ["AI in Medicine", "45%", "3,921 papers", BrainCircuit, "violet"], ["Cancer", "28%", "2,817 papers", HeartPulse, "pink"], ["Cardiovascular", "20%", "1,957 papers", HeartPulse, "coral"], ["Mental Health", "24%", "1,842 papers", BrainCircuit, "amber"], ["Neurology", "22%", "1,766 papers", BrainCircuit, "purple"], ["Diabetes & Metabolic", "18%", "2,103 papers", FlaskConical, "mint"], ["Infectious Diseases", "16%", "1,543 papers", ShieldCheck, "green"],
  ] as const;
  return <main className="aiotie-shell">
    <aside className="aiotie-nav"><div className="aiotie-brand"><img src="/aiotie-logo.png" alt="AIOTIE"/><div><strong>AIOTIE <span>Research</span></strong><small>Advanced Initiatives On Technology, Innovation &amp; Energy</small><em>Advancing Digital Health, Biomedical Informatics &amp; Data Ecosystems for Resilient Health Systems</em></div></div>
      <nav aria-label="Workspace navigation"><a className="selected" href="#research"><Sparkles/>Home</a><a href="#research"><BrainCircuit/>AI Chat</a><a href="#intelligence"><Globe2/>Research Intelligence <ChevronDown className="chev"/></a><div className="nav-sub"><a href="#intelligence"><Map/>Map</a><a href="#trends"><TrendingUp/>Trends</a><a href="#ideas"><Lightbulb/>Ideas</a></div><a href="#library"><BookOpen/>Evidence &amp; Literature <ChevronDown className="chev"/></a><a href="#documents"><FileText/>Papers</a><a href="#research"><FileSearch/>Protocols</a><a href="#research"><TrendingUp/>Statistics &amp; Data</a><a href="#library"><ShieldCheck/>Systematic Reviews</a><a href="#research"><FileText/>Manuscript</a><a href="#research"><UserRound/>Reviewer Mode</a><a href="#research"><BrainCircuit/>AI/ML Research</a><a href="#research"><BrainCircuit/>Research Memory</a><a href="#research"><Settings/>Settings</a></nav>
      <div className="partner-card"><img src="/aiotie-logo.png" alt=""/><p>Your research partner<br/>is always ready<br/>to help.</p><div className="wave">▁▃▅▇▅▃▁</div></div>
    </aside>
    <section className="aiotie-workbench" id="research"><header className="aiotie-topbar"><label className="global-search"><Search/><input value={question} onChange={(event) => setQuestion(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter") void submit(); }} placeholder="Ask anything about your research..."/><Mic/><button onClick={() => void submit()} aria-label="Search research"><Send/></button></label><div className="profile-actions"><button className="notification" aria-label="Notifications"><Bell/><i/></button><button className="partner-status"><i/>Research Partner</button><button className="profile"><span>UI</span>Dr. Usman Iqbal <ChevronDown/></button></div></header>
      <section className="intelligence" id="intelligence"><div className="intelligence-heading"><div className="heading-icon"><BrainCircuit/></div><div><h1>Research Intelligence Map</h1><p>Explore what&apos;s changing in medicine, discover emerging signals and find your next research opportunity.</p></div><div className="filters"><button><Globe2/>Global <ChevronDown/></button><button>Last 6 months <ChevronDown/></button></div></div><div className="map-tabs" role="tablist"><button className="tab-active">Map</button><button>Trends</button><button>Ideas</button></div>
        <div className="intelligence-map">{areas.map(([name, growth, papers, Icon, tone]) => <button className={`map-node ${tone}`} key={name} onClick={() => setQuestion(`${name}: `)}><span className="node-icon"><Icon/></span><span><strong>{name}</strong><b>↑ {growth}</b><small>{papers}</small></span></button>)}<div className="map-legend"><strong>Research Activity</strong><span><i className="hot"/>Very High</span><span><i className="high"/>High</span><span><i className="moderate"/>Moderate</span><span><i className="low"/>Low</span></div><div className="map-zoom"><Globe2/><button>+</button><button>−</button></div></div>
      </section>
      <section className="insight-grid"><article><header><h2><UserRound/>Latest Research Insights</h2><button>View All</button></header>{["New RCT shows promising results for CAR-T therapy in solid tumors", "Meta-analysis confirms GLP-1 reduces cardiovascular risk in type 2 diabetes", "New biomarker identified for early Alzheimer’s detection", "FDA approves first AI tool for automated pathology analysis"].map((item, index) => <button className="insight-row" key={item}><span className={`mini-icon i${index}`}>{index + 1}</span><span><strong>{item}</strong><small>{["Nature · 2 hours ago", "JAMA · 4 hours ago", "Lancet Neurology · 6 hours ago", "NEJM · 8 hours ago"][index]}</small></span><em>Verified</em><ChevronRight/></button>)}</article><article id="trends"><header><h2><TrendingUp/>Top Emerging Topics</h2><button aria-label="Close"><X/></button></header>{["AI in Radiology", "GLP-1 Agonist", "Long COVID", "mRNA Vaccines", "Precision Oncology"].map((topic, index) => <div className="trend-row" key={topic}><b>{index + 1}</b><strong>{topic}</strong><span className="spark"/><em>↑ {34 - index * 4}%</em></div>)}</article><article id="ideas"><header><h2><Lightbulb/>Your Personalized Ideas</h2><button>View All</button></header><p className="idea-kicker">Building on your interests</p><h3>Can AI predict chemotherapy response using multi-omics data?</h3><div className="tags"><span>Oncology</span><span>AI/ML</span><span>Biomarkers</span></div><hr/><p className="why">Why now?<br/><small>• Growing interest in multi-omics (↑ 42%)<br/>• Limited validation in real-world settings<br/>• Potential for personalized treatment</small></p><button className="explore">Explore Idea</button></article></section>
      <section className="research-composer"><input ref={fileInput} type="file" accept="application/pdf" hidden onChange={(event) => { const file = event.target.files?.[0]; if (file) void uploadDocument(file); event.target.value = ""; }}/><div className="composer-mark"><BrainCircuit/></div><textarea value={question} onChange={(event) => setQuestion(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter" && !event.shiftKey) { event.preventDefault(); void submit(); } }} placeholder="Ask me anything about your research..." aria-label="Research question"/><button onClick={() => fileInput.current?.click()} aria-label="Attach PDF"><Plus/></button><button aria-label="Voice input"><Mic/></button><button className="send" onClick={() => void submit()} aria-label="Send"><Send/></button></section>
      {(reply || analysis) && <section className="response-drawer" aria-live="polite"><strong>{reply}</strong>{analysis && <pre>{analysis}</pre>}</section>}
    </section>
    <aside className="signal-panel"><article className="opportunity"><header><Lightbulb/><strong>New Research Opportunity</strong><em>High Confidence</em></header><h2>AI-assisted radiology in low-resource settings</h2><p>Recent studies show strong performance of AI models in radiology, but external validation in low-resource hospitals is limited.</p><dl><div><dt>Evidence: 18 relevant studies</dt></div><div><dt>Potential research question:</dt><dd>Can an AI-assisted chest X-ray model maintain diagnostic performance across hospitals with different patient populations and imaging equipment?</dd></div><div><dt>Suggested design:</dt><dd>Prospective multicenter validation</dd></div></dl><footer><button onClick={() => setQuestion("AI-assisted radiology in low-resource settings: ")}>Explore Evidence</button><button onClick={() => setMode("Protocol builder")}>Build Protocol</button></footer></article>
      <article className="signals"><header><h2><HeartPulse/>Research Signals</h2><button>View All</button></header>{[["Emerging", "GLP-1 receptor agonists (2,341 papers)"], ["Growing", "Long COVID (1,892 papers)"], ["Growing", "AI in medical imaging (1,284 papers)"], ["Declining", "Vitamin D for COVID-19 (412 papers)"]].map(([state, item]) => <div key={item}><span className={state === "Declining" ? "down" : "up"}>{state === "Declining" ? "↓" : "↑"}</span><em className={state.toLowerCase()}>{state}</em><p>{item}</p></div>)}</article>
      <article className="interests"><h2>♥ Your Research Interests</h2><div className="tags"><span>Oncology</span><span>AI in Healthcare</span><span>Cardiology</span><span>Diabetes</span><span>Neurodegenerative</span><button>＋ Add</button></div></article>
      <article className="voice"><div><Mic/></div><p><strong>Voice Assistant</strong><small>Talk to AIOTIE</small></p></article>
      {sources.length > 0 && <article className="source-drawer" id="library"><h2>Retrieved evidence</h2>{sources.map((source) => <a key={source.id} href={source.url} target="_blank" rel="noreferrer"><strong>{source.title}</strong><small>{source.verificationStatus === "verified" ? "DOI verified" : "DOI unverified"}</small></a>)}</article>}
      {documents.length > 0 && <article className="document-drawer" id="documents"><h2>Papers</h2>{documents.map((document) => <button key={document.id} onClick={() => void openDocumentAnalysis(document)}><FileText/>{document.originalName}<small>{document.processingStatus === "analyzed" ? "Open analysis" : "Analyze paper"}</small></button>)}</article>}
    </aside>
  </main>;
}
