"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { BookOpen, ChevronRight, CircleHelp, FileText, FolderKanban, Mic, Paperclip, Plus, Search, Send, ShieldCheck, Sparkles } from "lucide-react";

type Mode = "Evidence synthesis" | "Paper analysis" | "Protocol builder" | "Statistical planning";
type Project = { id: string; name: string; question: string | null };
type Document = { id: string; originalName: string; byteSize: number; processingStatus: string };
const modes: { name: Mode; description: string; prompt: string }[] = [
  { name: "Evidence synthesis", description: "Find and assess current research", prompt: "What would you like to investigate? I’ll separate established findings from uncertainty and cite only sources we can verify." },
  { name: "Paper analysis", description: "Appraise a study, not just summarize it", prompt: "Attach a paper or paste its abstract. I’ll assess the design, risk of bias, applicability, and what the study does not prove." },
  { name: "Protocol builder", description: "Turn a question into a rigorous protocol", prompt: "Share your research idea. We’ll shape a focused question, appropriate design, outcomes, and safeguards together." },
  { name: "Statistical planning", description: "Plan analyses with assumptions visible", prompt: "Tell me the outcome, design, population, and estimand. I’ll help draft a transparent analysis plan." },
];
const prompts = ["Find current evidence", "Analyze a paper", "Build a PICO question", "Create a search strategy"];

export default function Home() {
  const [mode, setMode] = useState<Mode>("Evidence synthesis"); const [question, setQuestion] = useState(""); const [messages, setMessages] = useState<string[]>([]); const [reply, setReply] = useState(""); const [sources, setSources] = useState<{ id: string; title: string; journal: string | null; year: string | null; url: string; verificationStatus: "verified" | "unverified" }[]>([]); const [projects, setProjects] = useState<Project[]>([]); const [documents, setDocuments] = useState<Document[]>([]); const [analysis, setAnalysis] = useState(""); const [showProjectForm, setShowProjectForm] = useState(false); const [projectName, setProjectName] = useState(""); const [projectStatus, setProjectStatus] = useState(""); const fileInput = useRef<HTMLInputElement>(null);
  const active = useMemo(() => modes.find((item) => item.name === mode)!, [mode]);
  useEffect(() => { void fetch("/api/projects").then(async (response) => { if (response.ok) setProjects((await response.json() as { projects: Project[] }).projects); }).catch(() => undefined); }, []);
  useEffect(() => { void fetch("/api/documents").then(async (response) => { if (response.ok) setDocuments((await response.json() as { documents: Document[] }).documents); }).catch(() => undefined); }, []);
  const createProject = async () => { const name = projectName.trim(); if (name.length < 3) { setProjectStatus("Enter at least 3 characters."); return; } setProjectStatus("Saving…"); try { const response = await fetch("/api/projects", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ name, question: question.trim() || undefined }) }); const result = await response.json() as { project?: Project; error?: string }; if (!response.ok || !result.project) { setProjectStatus(result.error ?? "Unable to save project."); return; } setProjects((current) => [result.project!, ...current]); setProjectName(""); setShowProjectForm(false); setProjectStatus(""); } catch { setProjectStatus("Project storage is unavailable."); } };
  const uploadDocument = async (file: File) => { setReply("Uploading PDF securely…"); const data = new FormData(); data.append("file", file); try { const response = await fetch("/api/documents", { method: "POST", body: data }); const result = await response.json() as { document?: Document; error?: string }; if (!response.ok || !result.document) { setReply(result.error ?? "The document was not uploaded."); return; } setDocuments((current) => [result.document!, ...current]); setReply("PDF uploaded and queued for isolated extraction. Its contents have not yet been used to generate claims."); } catch { setReply("The document service is unavailable. No file was saved."); } };
  const analyzeDocument = async (document: Document) => { setReply("Analyzing the PDF as untrusted research material…"); setAnalysis(""); try { const response = await fetch("/api/documents/" + document.id + "/analyze", { method: "POST" }); const result = await response.json() as { analysis?: string; error?: string }; if (!response.ok || !result.analysis) { setReply(result.error ?? "The paper could not be analyzed."); return; } setDocuments((current) => current.map((item) => item.id === document.id ? { ...item, processingStatus: "analyzed" } : item)); setAnalysis(result.analysis); setReply("Paper analysis complete. Verify important claims against the original PDF."); } catch { setReply("The document analysis service is unavailable."); } };
  const submit = async () => { const value = question.trim(); if (!value) return; setMessages((current) => [...current, value]); setQuestion(""); setReply("Searching current literature…"); setSources([]); try { const response = await fetch("/api/research", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ mode, question: value }) }); const result = await response.json() as { message?: string; error?: string; sources?: { id: string; title: string; journal: string | null; year: string | null; url: string; verificationStatus: "verified" | "unverified" }[] }; setReply(result.message ?? result.error ?? "The research service could not process that request."); setSources(result.sources ?? []); } catch { setReply("The research service is unavailable. No claims or citations were generated."); } };
  return <main className="app-shell">
    <aside className="side-nav"><div className="brand"><span className="brand-mark">A</span><span>Aurelia</span></div><button className="new-research" onClick={() => setShowProjectForm((value) => !value)}><Plus size={17} /> New research</button>{showProjectForm && <form className="project-form" onSubmit={(event) => { event.preventDefault(); void createProject(); }}><label htmlFor="project-name">Project name</label><input id="project-name" value={projectName} onChange={(event) => setProjectName(event.target.value)} placeholder="e.g. Clinical AI review" /><button type="submit">Create project</button>{projectStatus && <small>{projectStatus}</small>}</form>}<nav aria-label="Workspace"><a className="active" href="#research"><Sparkles size={17} /> Research</a><a href="#projects"><FolderKanban size={17} /> Projects</a><a href="#library"><BookOpen size={17} /> Library</a><a href="#documents"><FileText size={17} /> Documents</a></nav><section className="project-list"><p>ACTIVE PROJECTS</p>{projects.length ? projects.map((project) => <button key={project.id}>{project.name}</button>) : <small>Sign in to save and view projects.</small>}</section><div className="safety"><ShieldCheck size={17}/><div><strong>Evidence-first</strong><small>Uncertainty is always visible</small></div></div></aside>
    <section className="workbench" id="research"><header className="topbar"><div><p className="eyebrow">RESEARCH WORKSPACE</p><h1>Good morning, Dr. Haider</h1></div><div className="top-actions"><button className="icon-button" aria-label="Help"><CircleHelp size={19}/></button><button className="avatar" aria-label="Profile">MH</button></div></header><div className="mode-row" role="tablist" aria-label="Research mode">{modes.map((item) => <button key={item.name} role="tab" aria-selected={mode === item.name} onClick={() => setMode(item.name)}><span>{item.name}</span><small>{item.description}</small></button>)}</div><article className="chat-card"><div className="assistant-orb">✦</div><p className="eyebrow accent">{mode.toUpperCase()}</p><h2>{active.prompt}</h2>{messages.length > 0 && <div className="conversation" aria-live="polite">{messages.map((message, index) => <div key={index} className="user-message">{message}</div>)}<div className="assistant-message"><strong>Research request captured.</strong> {reply || "I won’t infer citations or study results."}</div></div>}<div className="composer"><input ref={fileInput} type="file" accept="application/pdf" hidden onChange={(event) => { const file = event.target.files?.[0]; if (file) void uploadDocument(file); event.target.value = ""; }} /><textarea value={question} onChange={(event) => setQuestion(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter" && !event.shiftKey) { event.preventDefault(); void submit(); } }} placeholder="Ask a research question, upload a paper, or describe a study idea…" aria-label="Research question" /><div><button type="button" onClick={() => fileInput.current?.click()} aria-label="Attach PDF document" className="plain-button"><Paperclip size={18}/></button><button aria-label="Voice input" className="plain-button"><Mic size={18}/></button><span>Enter to send · Shift + Enter for a new line</span><button onClick={() => void submit()} className="send-button" aria-label="Send research request"><Send size={17}/></button></div></div></article><section className="prompt-section"><p>START WITH A FOCUSED TASK</p><div>{prompts.map((prompt) => <button key={prompt} onClick={() => setQuestion(prompt + ": ")}><ChevronRight size={16}/>{prompt}</button>)}</div>{documents.length > 0 && <div className="document-list">{documents.map((document) => <button key={document.id} onClick={() => void analyzeDocument(document)}><FileText size={15}/>{document.originalName} · {document.processingStatus === "analyzed" ? "Re-analyze" : "Analyze paper"}</button>)}</div>}{analysis && <article className="analysis-output"><p className="eyebrow accent">PAPER ANALYSIS</p><pre>{analysis}</pre></article>}</section></section>
    <aside className="evidence-panel"><div className="panel-title"><div><p className="eyebrow">LIVE CONTEXT</p><h2>Evidence desk</h2></div><span className="status"><i/> Ready</span></div><div className="notice"><ShieldCheck size={18}/><div><strong>Scientific integrity on</strong><p>Claims require verifiable sources. Advice is for research, not individual patient care.</p></div></div><section><div className="section-heading"><h3>Research activity</h3><button>View all</button></div><ol className="timeline"><li><i className="complete"/><div><strong>Methodology review complete</strong><p>AI validation framework</p><time>Today · 09:40</time></div></li><li><i/><div><strong>Screening queue</strong><p>14 abstracts awaiting review</p><time>Due tomorrow</time></div></li><li><i/><div><strong>Protocol draft</strong><p>Define primary outcome</p><time>In progress</time></div></li></ol></section><section><div className="section-heading"><h3>Retrieved evidence</h3><button>Library</button></div>{sources.length ? <div className="source-list">{sources.map((source) => <a key={source.id} href={source.url} target="_blank" rel="noreferrer"><strong>{source.title}</strong><span>{[source.journal, source.year].filter(Boolean).join(" · ") || "Europe PMC record"} · {source.verificationStatus === "verified" ? "DOI verified" : "DOI unverified"}</span></a>)}</div> : <div className="empty-evidence"><Search size={22}/><strong>No sources in this thread</strong><p>Searches and verified papers will appear here with evidence strength and citations.</p></div>}</section><footer>Model: Evidence-safe routing <span>•</span> Tools idle</footer></aside>
  </main>;
}
